import { test, expect } from '@playwright/test'
import { fakeEngineScript } from '../helpers/fake-neural-engine.js'

for (const layout of [
  {name:'compact',width:320,height:568,theme:'paper'},
  {name:'night',width:390,height:844,theme:'night'},
  {name:'desktop',width:1280,height:800,theme:'sepia'}
]) test(`lector sin paneles anidados y audio compacto: ${layout.name}`, async ({page}) => {
  test.setTimeout(60_000)
  await page.setViewportSize(layout)
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.addInitScript(fakeEngineScript({ installed:['piper:en_US-lessac-high'], hold:true }))
  await page.addInitScript(theme => {
    localStorage.setItem('inhouse-read-reading-preferences',JSON.stringify({theme,pdfMode:'text'}))
  },layout.theme)
  const errors=[]; page.on('pageerror',e=>errors.push(e.message))
  await page.goto('./')
  await page.locator('#file-picker').setInputFiles('tests/e2e/fixtures/reading-journey.pdf')
  await expect(page.locator('.pdf-reflow-page')).toBeVisible()
  await expect(page.locator('#reader-top-title')).not.toBeEmpty()
  await expect(page.locator('.header-actions')).toBeHidden()
  expect(await page.locator('#reader-back svg').evaluate(el=>getComputedStyle(el).stroke)).toBe(await page.locator('#reader-screen').evaluate(el=>getComputedStyle(el).color))
  await page.getByRole('button',{name:'Aspecto de lectura'}).click()
  await expect(page.getByRole('dialog',{name:'Texto',exact:true})).toBeVisible()
  await expect(page.locator('#reading-appearance .reading-details')).not.toHaveAttribute('open','')
  await expect(page.getByRole('slider',{name:'Interlineado',exact:true})).toBeHidden()
  await page.getByRole('button',{name:'Aumentar tamaño de letra'}).click()
  await expect(page.getByRole('slider',{name:'Tamaño de letra',exact:true})).toHaveValue('21')
  await page.getByRole('button',{name:'Reducir tamaño de letra'}).click()
  await expect(page.getByRole('slider',{name:'Tamaño de letra',exact:true})).toHaveValue('20')
  const bounds=await page.locator('.reading-panel').boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x+bounds.width).toBeLessThanOrEqual(layout.width)
  expect(bounds.y+bounds.height).toBeLessThanOrEqual(layout.height)
  expect(await page.locator('.reading-panel').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
  await page.screenshot({path:`test-results/reader-text-${layout.name}.png`})
  await page.getByRole('button',{name:'Cerrar opciones de lectura'}).click()
  await page.locator('#reader-location').click()
  await page.getByRole('button',{name:'Marcar esta página',exact:true}).click()
  await expect(page.getByRole('button',{name:'Quitar marcador de esta página'})).toHaveAttribute('aria-pressed','true')
  await expect(page.locator('[data-bookmarks]')).toContainText('Página 1')
  await page.getByRole('tab',{name:'Recientes'}).click()
  await expect(page.locator('[data-places=history]')).toBeVisible()
  await page.keyboard.press('Home')
  await expect(page.getByRole('tab',{name:'Marcadores'})).toBeFocused()
  await page.screenshot({path:`test-results/reader-content-${layout.name}.png`})
  await page.getByRole('button',{name:'Quitar marcador de esta página'}).click()
  await expect(page.locator('[data-bookmarks] .reading-place')).toHaveCount(0)
  await page.getByRole('button',{name:'Cerrar opciones de lectura'}).click()
  await page.getByRole('button',{name:'Escuchar el libro'}).click()
  await page.getByRole('button',{name:'Reproducir',exact:true}).click()
  await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible()
  await page.screenshot({path:`test-results/reader-audio-${layout.name}.png`})
  await page.getByRole('button',{name:'Cerrar opciones de lectura'}).click()
  const mini=page.locator('.reading-mini-player')
  await expect(mini).toBeVisible()
  await page.getByRole('button',{name:'Pausar lectura',exact:true}).click()
  await expect(mini).toContainText('En pausa')
  await page.getByRole('button',{name:'Continuar lectura',exact:true}).click()
  await expect(mini).toContainText('Leyendo')
  await page.screenshot({path:`test-results/reader-mini-${layout.name}.png`})
  await page.getByRole('button',{name:'Detener lectura',exact:true}).click()
  await expect(mini).toBeHidden()
  await expect(page.locator('#reader-screen')).not.toHaveClass(/has-reading-audio/)
  await page.getByRole('button',{name:'Volver a la estantería'}).click()
  // Returning an imported book creates its first 3D view. The header belongs
  // to the completed transition, not to the click while that view is preparing.
  await expect(page.locator('body')).not.toHaveClass(/is-closing-reader/,{timeout:30_000})
  await expect(page.locator('.header-actions')).toBeVisible()
  expect(errors).toEqual([])
})

test('la navegación sigue visible sobre el teclado del móvil', async ({page}) => {
  await page.setViewportSize({width:390,height:844})
  await page.addInitScript(() => {
    const viewport = new EventTarget()
    Object.assign(viewport,{width:390,height:844,offsetTop:0})
    Object.defineProperty(window,'visualViewport',{value:viewport,configurable:true})
    window.__readingViewport=viewport
  })
  await page.goto('./')
  await page.locator('#file-picker').setInputFiles('tests/e2e/fixtures/reading-journey.pdf')
  await expect(page.locator('.pdf-page-canvas')).toBeVisible()
  await page.locator('#reader-location').click()
  const field=page.getByRole('spinbutton',{name:'Ir a la página'})
  await field.focus()
  await page.evaluate(()=>{
    window.__readingViewport.height=340
    window.__readingViewport.dispatchEvent(new Event('resize'))
  })
  await expect.poll(async()=>{const box=await field.boundingBox();return box.y+box.height}).toBeLessThanOrEqual(340)
  await field.fill('3')
  await page.getByRole('button',{name:'Ir',exact:true}).click()
  await expect(page.locator('#reader-location')).toHaveAttribute('aria-label', /Página 3 de 4/)
  await expect(page.locator('.reader-return')).toContainText('Página 1 de 4')
})
