import { expect, test } from '@playwright/test';

test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:2});
test('isometric zoom preserves book interaction, promotes textures, pans and resets',async ({page})=>{
  test.setTimeout(90_000);
  await page.emulateMedia({reducedMotion:'reduce'});
  const errors=[]; page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(()=>localStorage.setItem('inhouse-read-shelf-plants',JSON.stringify([
    {key:'plant:zoom-test',seed:'zoom-test',catalogId:'sansevieria',variant:'sansevieria',potId:'muskot',width:42,height:124,shelf:0,x:.6}
  ])));
  await page.goto('/');
  await page.locator('#file-picker').setInputFiles('tests/e2e/fixtures/tiny.pdf');
  await expect(page.locator('.pdf-page-canvas')).toBeVisible();
  await page.getByRole('button',{name:'Volver a la estantería'}).click();
  await expect(page.locator('.ihr-flyout')).toHaveCount(0);
  await page.getByRole('button',{name:'Vista isométrica, libros de lado'}).click();
  const canvas=page.locator('.ihr-bookshelf-scene'), scroller=page.locator('.ihr-bookshelf__scroll');
  await expect(canvas).toHaveAttribute('data-view-progress','1');
  await expect(canvas).toHaveAttribute('data-animating','false');
  const initialHeight=await scroller.evaluate(node=>node.scrollHeight);
  await page.getByRole('button',{name:'Acercar estantería',exact:true}).click();
  await expect(canvas).toHaveAttribute('data-inspection-zoom','1.3000');
  await expect(canvas).toHaveAttribute('data-high-resolution-books','1');
  await expect(canvas).toHaveAttribute('data-high-resolution-plants','1');
  expect(await scroller.evaluate(node=>node.scrollHeight)).toBe(initialHeight);
  const frame=await canvas.boundingBox();
  await page.mouse.move(frame.x+frame.width*.8,frame.y+frame.height*.4);
  await page.mouse.down(); await page.mouse.move(frame.x+frame.width*.8+55,frame.y+frame.height*.4,{steps:5}); await page.mouse.up();
  await expect.poll(async()=>JSON.parse(await canvas.getAttribute('data-inspection-pan'))[0]).toBeGreaterThan(40);
  await page.waitForTimeout(300);
  await page.locator('.ihr-spine').first().click({timeout:10_000});
  await expect(page.getByRole('button',{name:/Toca para leer/})).toBeVisible();
  await page.getByRole('button',{name:'Cerrar',exact:true}).click();
  await expect(page.locator('.ihr-flyout')).toHaveCount(0);
  await expect(canvas).toHaveAttribute('data-animating','false');
  await page.getByRole('button',{name:'Ver estantería completa',exact:true}).click();
  await expect(canvas).toHaveAttribute('data-inspection-zoom','1.0000');
  await expect(canvas).toHaveAttribute('data-full-cabinet-in-frame','true');
  await page.mouse.move(frame.x+frame.width/2,frame.y+frame.height/2);
  await page.mouse.wheel(0,-150);
  await expect.poll(async()=>Number(await canvas.getAttribute('data-inspection-zoom'))).toBeGreaterThan(1.1);
  await page.getByRole('button',{name:'Ver estantería completa',exact:true}).click();
  const bounds=await canvas.boundingBox(), x=bounds.x+bounds.width/2,y=bounds.y+Math.min(190,bounds.height/2);
  const cdp=await page.context().newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:x-35,y},{id:2,x:x+35,y}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:x-70,y:y+20},{id:2,x:x+70,y:y+20}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await expect.poll(async()=>Number(await canvas.getAttribute('data-inspection-zoom'))).toBeGreaterThan(1.8);
  await expect(page.locator('.ihr-spine.is-dragging')).toHaveCount(0);
  await page.getByRole('button',{name:'Ver estantería completa',exact:true}).click();
  await page.getByRole('button',{name:'Vista de canto',exact:true}).click();
  await expect(page.getByRole('group',{name:'Zoom de la estantería',exact:true})).toBeHidden();
  expect(errors).toEqual([]);
});
