import { test, expect } from '@playwright/test'

test('lomo nítido: tintas, metales y grabado persistentes en móvil', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.emulateMedia({reducedMotion:'reduce'})
  const errors=[]; page.on('pageerror', e=>errors.push(e.message))
  await page.goto('./')
  await page.locator('#file-picker').setInputFiles('tests/e2e/fixtures/reading-journey.pdf')
  await expect(page.locator('.pdf-page-canvas')).toBeVisible()
  await expect(page.locator('#reader-location')).toContainText('Página 1')
  await page.getByRole('button',{name:'Volver a la estantería'}).click()
  await page.locator('.ihr-spine').first().click()
  await page.getByRole('button',{name:'Editar',exact:true}).click()
  await page.getByLabel('Texto del lomo',{exact:true}).fill('El jardín secreto')
  await page.getByLabel('Fuente del lomo',{exact:true}).selectOption('Lora')
  const changeColor = async (label,color) => page.getByLabel(label,{exact:true}).evaluate((input,value)=>{
    input.value=value; input.dispatchEvent(new Event('change',{bubbles:true}))
  },color)
  await changeColor('Elegir otro color para el lomo','#254935')
  await changeColor('Color del texto','#fff5db')
  await page.getByLabel('Acabado del texto').selectOption('gold')
  await page.getByRole('switch',{name:'Texto grabado'}).check()
  await expect(page.locator('.ihr-flyout__book canvas')).toHaveAttribute('data-angle','90')
  // Wait for the debounced upload before comparing the actual GPU snapshot.
  await expect.poll(()=>page.locator('.ihr-flyout__book canvas').evaluate(c=>c.toDataURL())).not.toBe('data:,')
  await page.waitForTimeout(350)
  await page.screenshot({path:'test-results/spine-editor-gold.png'})
  await page.getByLabel('Acabado del lomo').selectOption('gold')
  await expect.poll(()=>page.locator('.ihr-flyout__book canvas').evaluate(c=>c.toDataURL())).not.toBe('data:,')
  await page.waitForTimeout(100)
  await page.screenshot({path:'test-results/spine-binding-gold.png'})
  const gold=await page.locator('.ihr-flyout__book canvas').evaluate(c=>c.toDataURL())
  await page.getByLabel('Acabado del texto').selectOption('silver')
  await expect.poll(()=>page.locator('.ihr-flyout__book canvas').evaluate(c=>c.toDataURL())).not.toBe(gold)
  await page.screenshot({path:'test-results/spine-editor-silver-text.png'})
  await page.getByRole('button',{name:'Listo',exact:true}).click()
  await page.getByRole('button',{name:'Cerrar',exact:true}).click()
  await page.reload()
  const spine=page.locator('.ihr-spine').first()
  await expect(spine).toBeVisible()
  expect(await spine.locator('canvas').evaluate(c=>c.width/c.getBoundingClientRect().width)).toBeGreaterThanOrEqual(1.9)
  await page.screenshot({path:'test-results/spine-shelf-sharp.png'})
  await spine.click()
  await page.getByRole('button',{name:'Editar',exact:true}).click()
  await expect(page.getByRole('switch',{name:'Texto grabado'})).toBeChecked()
  await expect(page.getByLabel('Acabado del texto')).toHaveValue('silver')
  await expect(page.getByLabel('Texto del lomo',{exact:true})).toHaveValue('El jardín secreto')
  const goldBinding = await page.locator('.ihr-flyout__book canvas').evaluate(c=>c.toDataURL())
  await page.getByLabel('Acabado del lomo').selectOption('silver')
  await expect.poll(()=>spine.evaluate(n=>n.style.getPropertyValue('--ihr-spine-base'))).toBe('#d5dce3')
  await expect.poll(()=>page.locator('.ihr-flyout__book canvas').evaluate(c=>c.toDataURL())).not.toBe(goldBinding)
  await page.screenshot({path:'test-results/spine-binding-silver.png'})
  await page.getByLabel('Acabado del lomo').selectOption('gold')
  await expect.poll(()=>spine.evaluate(n=>n.style.getPropertyValue('--ihr-spine-base'))).toBe('#d6ad55')
  await page.getByRole('button',{name:'Auto',exact:true}).click()
  await expect(page.getByLabel('Acabado del texto')).toHaveValue('matte')
  expect(errors).toEqual([])
})
