// Generated by executing the pinned official hebrew_ipa.py, not by the JavaScript port.
// Source: OHF-Voice/piper1-gpl efffbfb226bfb511ebbcf55d0cecd8b35a89743d.
export const NAKDIMON_ORACLE = {
  text: 'הכוח לשנות מתחיל ברגע שבו אתה מאמין שזה אפשרי!',
  dotted: 'הַכּוֹחַ לְשַׁנּוֹת מַתְחִיל בָּרֶגַע שֶׁבּוֹ אַתָּה מַאֲמִין שֶׁזֶּה אֶפְשָׁרִי!'
}

export const IPA_ORACLES = [
  ['נִרְאֵית', 'nˈiʁejt'],
  ['לְעֵינֵינוּ', 'leejnejnˈu'],
  ['בְּטִפּוֹת', 'betipˈot'],
  ['יִשְׁמְרוּ', 'jiʃmeʁˈu'],
  ['מְדַבְּרִים', 'medabeʁˈim'],
  ['הַכּוֹחַ', 'hakoχˈa'],
  ['שָׁלוֹם', 'ʃˈalom'],
  ['מֶלֶךְ', 'mˈeleχ'],
  ['בָּרֶגַע', 'baʁegˈa'],
  ['מַאֲמִין', 'maamˈin'],
  ['שֶׁזֶּה', 'ʃezˈe'],
  ['אֶפְשָׁרִי!', 'efʃaʁˈi'],
  ['שָׁנָה', 'ʃanˈa'],
  ['שָׁנָה.', 'ʃˈanah'],
  ['גַּם', 'gˈam'],
  ['שׁוּק', 'ʃˈuk'],
  ['צוּר', 'tsˈuʁ'],
  ['צַ׳י', ''],
  ['גַ׳ז', ''],
  ['תּוֹדָה', 'todˈa'],
  ['כָּל', 'kˈal'],
  ['כׇּל', 'kˈol'],
  ['רוּחַ', 'ʁuχˈa'],
  ['אֱמֶת', 'ˈemet'],
  ['שָֽׁלוֹם', 'ʃˈalom'],
  ['שָׁלוֹם  עוֹלָם', 'ʃˈalom ʔˈolam'],
  ['שלום', ''],
  ['...', ''],
  [NAKDIMON_ORACLE.dotted, 'hakoχˈa leʃanˈot mˈatχil baʁegˈa ʃebˈo atˈa maamˈin ʃezˈe efʃaʁˈi']
]

// Python str.isdigit() characters whose Unicode category is not Nd.
export const NON_DECIMAL_DIGIT_RANGES = [
  [178, 179], [185, 185], [4969, 4977], [6618, 6618], [8304, 8304], [8308, 8313],
  [8320, 8329], [9312, 9320], [9332, 9340], [9352, 9360], [9450, 9450], [9461, 9469],
  [9471, 9471], [10102, 10110], [10112, 10120], [10122, 10130], [68160, 68163],
  [69216, 69224], [69714, 69722], [127232, 127242]
]
